CREATE TABLE IF NOT EXISTS drinking
(
    drinking_id        BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    drinking_type      VARCHAR(255),
    description        TEXT,
    CONSTRAINT pk_drinking PRIMARY KEY (drinking_id)
);

CREATE TABLE IF NOT EXISTS ingredient
(
    ingredient_id      BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    item               VARCHAR(255),
    description        TEXT,
    value              DOUBLE PRECISION,
    value_unit         VARCHAR(255),
    price              DOUBLE PRECISION,
    CONSTRAINT pk_ingredient PRIMARY KEY (ingredient_id)
);

CREATE TABLE IF NOT EXISTS composition
(
    composition_id     BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    description        TEXT,
    preparation        JSONB,
    CONSTRAINT pk_composition PRIMARY KEY (composition_id)
);

CREATE TABLE IF NOT EXISTS composition_ingredients
(
    composition_id BIGINT NOT NULL,
    ingredients_id BIGINT NOT NULL
);

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'uc_composition_ingredients_ingredients_ingredient') THEN
            ALTER TABLE composition_ingredients
                ADD CONSTRAINT uc_composition_ingredients_ingredients_ingredient UNIQUE (composition_id, ingredients_id);
        END IF;
    END
$$;

ALTER TABLE IF EXISTS composition_ingredients
    ADD CONSTRAINT fk_coming_on_composition FOREIGN KEY (composition_id) REFERENCES composition (composition_id);

ALTER TABLE IF EXISTS composition_ingredients
    ADD CONSTRAINT fk_coming_on_ingredient FOREIGN KEY (ingredients_id) REFERENCES ingredient (ingredient_id);