server:
  port: 8085

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/una_learn?currentSchema=learn
    username: user
    password: usermdp
    type: com.zaxxer.hikari.HikariDataSource

  flyway:
    baseline-on-migrate: true
    schemas: learn
    out-of-order: false
    connect-retries: 2
    connect-retries-interval: 2